# -*- coding: utf-8 -*-
"""Sampler_division_fase.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tF7vo8nMH6jZWNYlXdC4TLE6y-AJ43Vy
"""

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

"""Cargar ruta del audio que se procesará (Corrección de Fase)"""

import os
import shutil

# Ruta del archivo generado en Colab
ruta_origen = "/content/Processed_Audio_Colab/Piano_Balance_Norm_V7.wav"

# Ruta de destino en Google Drive
# Se creará si no existe
carpeta_destino_drive = "/content/drive/MyDrive/Processed_Audio_Colab"
os.makedirs(carpeta_destino_drive, exist_ok=True)

ruta_destino = os.path.join(carpeta_destino_drive, "Piano_Balance_Norm_V7.wav")

# Mover el archivo
try:
    shutil.move(ruta_origen, ruta_destino)
    print(f"✅ Archivo movido con éxito a: {ruta_destino}")
    print("Ahora puedes encontrarlo en tu Google Drive y descargarlo desde allí.")
except FileNotFoundError:
    print(f"❌ ERROR: El archivo de origen no se encontró en {ruta_origen}. Asegúrate de que el procesamiento anterior se haya ejecutado correctamente.")
except Exception as e:
    print(f"❌ Ocurrió un error al intentar mover el archivo: {e}")

import os

# Listar el contenido de la carpeta MyDrive para verificar la ruta del archivo
print("Contenido de /content/drive/MyDrive/:")
for root, dirs, files in os.walk('/content/drive/MyDrive/'):
    for file in files:
        if 'piano-model-mt-5-piano-mvsep.wav' in file:
            print(os.path.join(root, file))
    if not dirs and not files and root == '/content/drive/MyDrive/': # Check if MyDrive is empty
        print("La carpeta /content/drive/MyDrive/ parece estar vacía o no es accesible.")
        break # Exit if MyDrive is empty to avoid iterating unnecessary subdirectories
    # Limit the depth of search to avoid long execution times for large drives
    if root.count(os.sep) - '/content/drive/MyDrive/'.count(os.sep) > 2: # Limit to 2 subdirectories deep
        del dirs[:]

"""Cálculo de diferencia de fase


"""

import librosa
import numpy as np

print("1. Computing STFT for left and right channels...")
# 1. Compute the Short-Time Fourier Transform (STFT) for the left channel
stft_left = librosa.stft(y_original_stereo[0])

# 2. Compute the STFT for the right channel
stft_right = librosa.stft(y_original_stereo[1])

print("2. Calculating instantaneous phase for both channels...")
# 3. Calculate the phase for the left channel
phase_left = np.angle(stft_left)

# 4. Calculate the phase for the right channel
phase_right = np.angle(stft_right)

print("3. Computing the phase difference...")
# 5. Compute the phase difference
phase_difference_array = phase_left - phase_right

# 6. Print the shape of phase_difference_array
print(f"✅ Phase difference array computed. Shape: {phase_difference_array.shape}")

"""### Cargar audio original para análisis

"""

import librosa
import os

# Ensure ARCHIVO_INPUT is defined from previous steps
# If not, uncomment and define it here:
ARCHIVO_INPUT = '/content/drive/MyDrive/Processed_Audio_Colab/MVSep Piano UI/piano-model-mt-5-piano-mvsep.wav'

if 'ARCHIVO_INPUT' not in globals():
    print("❌ ERROR: ARCHIVO_INPUT no está definido. Asegúrate de que las celdas anteriores se hayan ejecutado.")
else:
    if not os.path.exists(ARCHIVO_INPUT):
        print(f"❌ ERROR: El archivo original no se encontró en {ARCHIVO_INPUT}.")
    else:
        print(f"Cargando archivo original para análisis de fase desde: {ARCHIVO_INPUT}")
        # Load the audio file, preserving original sample rate and as a stereo signal
        y_original_stereo, sr_original = librosa.load(ARCHIVO_INPUT, sr=None, mono=False)

        print(f"✅ Audio original cargado con éxito. Shape: {y_original_stereo.shape}, Sample Rate: {sr_original} Hz")

"""### Detector de Comienzos de Nota (Onsets)

Esta sección cargará el archivo de audio especificado y utilizará la biblioteca `librosa` para identificar los momentos en que comienza una nueva nota o un evento sonoro significativo.
"""

import librosa
import numpy as np
import os # Import os for path checking

# Asegurarse de que ARCHIVO_INPUT esté definido (tomado de la configuración anterior)
# Si no estuviera definido, descomentar la siguiente línea y especificar la ruta:

ARCHIVO_INPUT = "/content/drive/MyDrive/Processed_Audio_Colab/MVSep Piano UI/piano-model-mt-5-piano-mvsep.wav"

if not os.path.exists(ARCHIVO_INPUT):
    print(f"❌ ERROR: El archivo de origen no se encontró en {ARCHIVO_INPUT}.")
    print("Por favor, verifica que el archivo existe en tu Google Drive en la ruta especificada.")
    print("Si el archivo existe, intenta volver a montar Google Drive ejecutando la celda de `drive.mount()` al inicio del cuaderno.")
else:
    # Cargar el archivo de audio. Usamos mono=True para la detección de onsets por simplicidad.
    # Es importante que el sample rate sea el mismo que el usado en el procesamiento anterior si fuera relevante.
    print(f"Cargando audio para detección de onsets desde: {ARCHIVO_INPUT}")
    y_onset, sr_onset = librosa.load(ARCHIVO_INPUT, sr=None, mono=True)

    print("Audio cargado. Iniciando detección de onsets...")

import librosa # Import librosa
import numpy as np # Import numpy for array creation
import gc # Import garbage collector

# Ensure ARCHIVO_INPUT is defined. It should come from previous cells like 1f95a1cc.
# As a fallback, define it here if not found.
if 'ARCHIVO_INPUT' not in globals():
    ARCHIVO_INPUT = "/content/drive/MyDrive/Processed_Audio_Colab/MVSep Piano UI/piano-model-mt-5-piano-mvsep.wav"
    print(f"⚠️ Advertencia: ARCHIVO_INPUT no encontrado en el ámbito global. Definiendo para esta celda: {ARCHIVO_INPUT}")

# Load the audio for onset detection within this cell to ensure y_onset is defined.
# This prevents NameError if preceding cells were not executed or kernel was reset.
print(f"Cargando audio para detección de onsets desde: {ARCHIVO_INPUT}")
y_onset, sr_onset = librosa.load(ARCHIVO_INPUT, sr=None, mono=True)
print("Audio cargado para onsets.")

# 1. Detectar los 'onsets' (comienzos de nota)
# Utilizaremos el algoritmo de detección de onsets de librosa. Es sensible a los parámetros.
# Por defecto, el `onset_detector` de librosa calcula una función de detección de onsets (ODF)
# y luego aplica un algoritmo de selección de picos para encontrar los onsets.

onset_frames = librosa.onset.onset_detect(y=y_onset, sr=sr_onset, units='frames', backtrack=True)
onset_times_raw = librosa.frames_to_time(onset_frames, sr=sr_onset)

# Almacenar los tiempos de onset en un array de NumPy
onsets_array = np.array(onset_times_raw)

print(f"Se detectaron {len(onsets_array)} onsets.")
print("Primeros 10 onsets detectados (en segundos): ")
print(onsets_array[:10])

# Liberar memoria del audio original que ya no se necesita
del y_onset, onset_times_raw
gc.collect()
print("✅ Memoria de 'y_onset' liberada.")

"""## CORRECCIÓN DE FASE

### Modificar la corrección de fase usando Chunking
"""

import librosa
import numpy as np
import soundfile as sf
import os
import gc # For garbage collection
import shutil # For copying files

# --- Chunking Parameters (Instruction 1) ---
chunk_duration_seconds = 30 # Process 30 seconds of audio at a time
n_fft = 2048 # FFT window size
hop_length = 512 # Hop length for STFT

# --- Define ARCHIVO_INPUT explicitly for this cell's execution context ---
ARCHIVO_INPUT = '/content/drive/MyDrive/Processed_Audio_Colab/MVSep Piano UI/piano-model-mt-5-piano-mvsep.wav'
LOCAL_TEMP_ORIGINAL_AUDIO_PATH = '/content/.temp_original_audiowav'
# ---------------------------------------------------------------------------

# --- Define Output Folder and Parameters (Moved from previous setup cell for robustness) ---
OUTPUT_FOLDER_PHASE_CORRECTIONS = "/content/drive/MyDrive/Processed_Audio_Colab/Phase_Corrections"
os.makedirs(OUTPUT_FOLDER_PHASE_CORRECTIONS, exist_ok=True)
PHASE_CORRECTION_PRIORITY_CHANNEL = 'L' # @param ['L', 'R']
# ---------------------------------------------------------------------------------------

if not os.path.exists(ARCHIVO_INPUT):
    print(f"❌ ERROR: The original audio file was not found at {ARCHIVO_INPUT}.")
    exit()

# --- Copy original file to a local Colab directory for robust access ---
print(f"Copiando el archivo original desde Google Drive a {LOCAL_TEMP_ORIGINAL_AUDIO_PATH}...")
try:
    shutil.copy(ARCHIVO_INPUT, LOCAL_TEMP_ORIGINAL_AUDIO_PATH)
    print("Copia exitosa. Usando el archivo local para el procesamiento de fase.")
except FileNotFoundError:
    print(f"❌ ERROR: El archivo de origen no se encontró en {ARCHIVO_INPUT}. Asegùrate de que exista en tu Drive.")
    exit()
except Exception as e:
    print(f"❌ Ocurrió un error al copiar el archivo: {e}")
    exit()
# ---------------------------------------------------------------------

# Load the entire original audio file once (Instruction 2) from the local path
print(f"Loading entire original audio for phase correction from: {LOCAL_TEMP_ORIGINAL_AUDIO_PATH}")
y_original_stereo, sr_original = librosa.load(LOCAL_TEMP_ORIGINAL_AUDIO_PATH, sr=None, mono=False)
print(f"✅ Original audio loaded. Shape: {y_original_stereo.shape}, Sample Rate: {sr_original} Hz")

# Calculate samples per chunk after loading sr_original
samples_per_chunk = int(sr_original * chunk_duration_seconds)
print(f"Processing in chunks of {chunk_duration_seconds} seconds ({samples_per_chunk} samples).")

# Compute full STFTs and phase difference array for the entire audio once (Instruction 3)
print("1. Computing full STFT for left and right channels...")
stft_left_orig_full = librosa.stft(y_original_stereo[0], n_fft=n_fft, hop_length=hop_length)
stft_right_orig_full = librosa.stft(y_original_stereo[1], n_fft=n_fft, hop_length=hop_length)

print("2. Calculating instantaneous phase for both full channels...")
phase_left_orig_full = np.angle(stft_left_orig_full)
phase_right_orig_full = np.angle(stft_right_orig_full)

print("3. Computing the full phase difference array...")
phase_difference_array_full = phase_left_orig_full - phase_right_orig_full
print(f"✅ Full phase difference array computed. Shape: {phase_difference_array_full.shape}")

print(f"Starting chunk-based phase correction with priority channel: {PHASE_CORRECTION_PRIORITY_CHANNEL}")

output_filename = "Phase_Corrected_Audio_Chunked.wav"
output_path = os.path.join(OUTPUT_FOLDER_PHASE_CORRECTIONS, output_filename)

# Open the output WAV file in write mode using soundfile (Instruction 4)
# soundfile automatically handles creating the file with correct headers from the first write
with sf.SoundFile(output_path, 'w', sr_original, y_original_stereo.shape[0], format='WAV') as f_out:
    total_samples = y_original_stereo.shape[1]
    processed_samples = 0
    current_stft_frame_idx = 0

    # Implement a for loop to iterate through the audio in chunks (Instruction 5)
    for i in range(0, total_samples, samples_per_chunk):
        chunk_start_sample = i
        chunk_end_sample = min(i + samples_per_chunk, total_samples)
        current_chunk_sample_length = chunk_end_sample - chunk_start_sample

        if current_chunk_sample_length <= 0:
            continue

        # Extract the stereo audio chunk
        y_original_stereo_chunk = y_original_stereo[:, chunk_start_sample:chunk_end_sample]

        # Compute STFTs and their magnitudes/phases for the current chunk (Instruction 6)
        stft_left_chunk = librosa.stft(y_original_stereo_chunk[0], n_fft=n_fft, hop_length=hop_length)
        stft_right_chunk = librosa.stft(y_original_stereo_chunk[1], n_fft=n_fft, hop_length=hop_length)

        magnitude_left_chunk = np.abs(stft_left_chunk)
        magnitude_right_chunk = np.abs(stft_right_chunk)
        phase_left_chunk = np.angle(stft_left_chunk)
        phase_right_chunk = np.angle(stft_right_chunk)

        # Determine the number of frames for the current chunk's STFT
        n_frames_chunk = stft_left_chunk.shape[1]

        # Extract the corresponding phase_difference_array_chunk (Instruction 7)
        phase_difference_array_chunk = phase_difference_array_full[:, current_stft_frame_idx : current_stft_frame_idx + n_frames_chunk]

        # Ensure lengths match in case of slight discrepancies at the end of audio
        if phase_difference_array_chunk.shape[1] != n_frames_chunk:
            # This can happen if the last chunk is smaller than n_fft/hop_length calculation implies
            # Adjust phase_difference_array_chunk to match the actual frames of the current STFT
            phase_difference_array_chunk = librosa.util.fix_length(phase_difference_array_chunk, size=n_frames_chunk, axis=1)

        # Apply phase correction on the *_chunk variables (Instruction 8)
        corrected_phase_non_priority_chunk = None
        magnitude_non_priority_chunk = None
        corrected_stft_priority_chunk = None # To hold the original STFT for the priority channel

        if PHASE_CORRECTION_PRIORITY_CHANNEL == 'L':
            # Correct right channel's phase using the difference (L - R) as an offset to R's original phase
            corrected_phase_non_priority_chunk = phase_right_chunk + phase_difference_array_chunk
            magnitude_non_priority_chunk = magnitude_right_chunk
            corrected_stft_priority_chunk = stft_left_chunk # Left channel magnitude and phase unchanged

        elif PHASE_CORRECTION_PRIORITY_CHANNEL == 'R':
            # Correct left channel's phase using the difference (R - L) as an offset to L's original phase
            corrected_phase_non_priority_chunk = phase_left_chunk - phase_difference_array_chunk # Apply negative difference
            magnitude_non_priority_chunk = magnitude_left_chunk
            corrected_stft_priority_chunk = stft_right_chunk # Right channel magnitude and phase unchanged

        # Reconstruct STFT for the corrected non-priority channel
        corrected_stft_non_priority_chunk = magnitude_non_priority_chunk * np.exp(1j * corrected_phase_non_priority_chunk)

        # Perform Inverse STFT to convert back to time domain (Instruction 9)
        y_corrected_non_priority_chunk = librosa.istft(corrected_stft_non_priority_chunk, hop_length=hop_length, length=current_chunk_sample_length)

        # Also inverse STFT the priority channel (its magnitude and phase were kept)
        y_corrected_priority_chunk = librosa.istft(corrected_stft_priority_chunk, hop_length=hop_length, length=current_chunk_sample_length)

        # Combine the corrected channels into y_corrected_stereo_chunk (Instruction 10)
        y_corrected_stereo_chunk = np.empty((2, current_chunk_sample_length), dtype=y_original_stereo.dtype)
        if PHASE_CORRECTION_PRIORITY_CHANNEL == 'L':
            y_corrected_stereo_chunk[0] = y_corrected_priority_chunk
            y_corrected_stereo_chunk[1] = y_corrected_non_priority_chunk
        else: # PHASE_CORRECTION_PRIORITY_CHANNEL == 'R'
            y_corrected_stereo_chunk[0] = y_corrected_non_priority_chunk
            y_corrected_stereo_chunk[1] = y_corrected_priority_chunk

        # Write y_corrected_stereo_chunk to the output WAV file (Instruction 11)
        f_out.write(y_corrected_stereo_chunk.T)

        processed_samples += current_chunk_sample_length
        current_stft_frame_idx += n_frames_chunk

        print(f"   Processed {processed_samples / sr_original:.2f} / {total_samples / sr_original:.2f} seconds ({100 * processed_samples / total_samples:.2f}%)")

        # Release memory for chunk-specific variables (Instruction 12)
        del y_original_stereo_chunk, stft_left_chunk, stft_right_chunk, magnitude_left_chunk, magnitude_right_chunk, \
            phase_left_chunk, phase_right_chunk, phase_difference_array_chunk, corrected_phase_non_priority_chunk, \
            magnitude_non_priority_chunk, corrected_stft_non_priority_chunk, y_corrected_non_priority_chunk, \
            y_corrected_priority_chunk, corrected_stft_priority_chunk, y_corrected_stereo_chunk
        gc.collect()

print(f"✅ Phase correction completed and saved to {output_path}")

# Release memory for large full audio arrays (Instruction 13)
del y_original_stereo, stft_left_orig_full, stft_right_orig_full, phase_left_orig_full, phase_right_orig_full, phase_difference_array_full
gc.collect()

"""Visualización de forma de onda de los Onsets resultantes de la corrección"""

import matplotlib.pyplot as plt
import numpy as np
import librosa
import soundfile as sf # To load the corrected audio
import os

# 1. Define the duration of the segment to visualize (in seconds)
segment_duration = 0.05

# --- Ensure ARCHIVO_INPUT is defined (fallback) ---
if 'ARCHIVO_INPUT' not in globals():
    ARCHIVO_INPUT = '/content/drive/MyDrive/Processed_Audio_Colab/MVSep Piano UI/piano-model-mt-5-piano-mvsep.wav'
    print(f"⚠️ Advertencia: ARCHIVO_INPUT no encontrado en el ámbito global. Definiendo para esta celda: {ARCHIVO_INPUT}")
else:
    ARCHIVO_INPUT = globals()['ARCHIVO_INPUT'] # Use the globally defined one

# --- Ensure y_original_stereo and sr_original are available (fallback) ---
y_original_stereo = globals().get('y_original_stereo', None)
sr_original = globals().get('sr_original', None)

if y_original_stereo is None or sr_original is None:
    print(f"⚠️ Advertencia: y_original_stereo o sr_original no encontrados en el ámbito global o son None. Cargando audio original desde: {ARCHIVO_INPUT}")
    if not os.path.exists(ARCHIVO_INPUT):
        print(f"❌ ERROR: El archivo original no se encontró en {ARCHIVO_INPUT}. No se puede visualizar sin él.")
        exit() # Cannot proceed without original audio
    try:
        y_original_stereo, sr_original = librosa.load(ARCHIVO_INPUT, sr=None, mono=False)
        print(f"✅ Audio original cargado con éxito. Shape: {y_original_stereo.shape}, Sample Rate: {sr_original} Hz")
    except Exception as e:
        print(f"❌ ERROR al cargar audio original con librosa.load: {e}")
        exit() # Exit if loading fails

# --- Ensure onsets_array is available (fallback) ---
onsets_array = None
# Corrected condition to avoid TypeError on len(None)
if 'onsets_array' not in globals() or globals()['onsets_array'] is None or len(globals()['onsets_array']) == 0:
    print("❌ ERROR: 'onsets_array' no se encontró o está vacío. Re-detectando onsets para la visualización.")
    # Re-load mono audio for onset detection
    y_onset_fallback, sr_onset_fallback = librosa.load(ARCHIVO_INPUT, sr=None, mono=True)
    onset_frames_fallback = librosa.onset.onset_detect(y=y_onset_fallback, sr=sr_onset_fallback, units='frames')
    onsets_array = np.array(librosa.frames_to_time(onset_frames_fallback, sr=sr_onset_fallback))
    if len(onsets_array) == 0:
        print("❌ ERROR: No se pudieron detectar onsets incluso con la re-detección. No se puede visualizar.")
        exit()
    print(f"✅ Onsets re-detectados: {len(onsets_array)} onsets.")
else:
    onsets_array = globals()['onsets_array']

# --- Ensure output_path from c0ab278d is accessible ---
corrected_audio_path = None
if 'output_path' not in globals() or not os.path.exists(globals()['output_path']):
    # Fallback if output_path is not defined or the file doesn't exist
    # Try to infer it from the known structure if possible, or exit
    inferred_output_path = "/content/drive/MyDrive/Processed_Audio_Colab/Phase_Corrections/Phase_Corrected_Audio_Chunked.wav"
    if os.path.exists(inferred_output_path):
        corrected_audio_path = inferred_output_path
        print(f"⚠️ Advertencia: 'output_path' no definida. Usando ruta inferida para audio corregido: {corrected_audio_path}")
    else:
        print(f"❌ ERROR: El archivo de audio corregido no se encontró en '{inferred_output_path}' y la variable 'output_path' no está definida. Asegúrate de que la celda de corrección de fase (c0ab278d) se haya ejecutado correctamente.")
        exit() # Cannot proceed without corrected audio path
else:
    corrected_audio_path = globals()['output_path']

# Debugging prints
print(f"DEBUG: onsets_array is not None: {onsets_array is not None}")
if onsets_array is not None:
    print(f"DEBUG: len(onsets_array) > 0: {len(onsets_array) > 0}")
print(f"DEBUG: y_original_stereo is not None: {y_original_stereo is not None}")
print(f"DEBUG: sr_original is not None: {sr_original is not None}")
print(f"DEBUG: corrected_audio_path is not None: {corrected_audio_path is not None}")
if corrected_audio_path is not None:
    print(f"DEBUG: os.path.exists(corrected_audio_path): {os.path.exists(corrected_audio_path)}")

# Proceed with plotting only if all necessary variables are now defined and not None
if all([onsets_array is not None, len(onsets_array) > 0, y_original_stereo is not None, sr_original is not None, corrected_audio_path is not None, os.path.exists(corrected_audio_path)]):
    first_onset_time = onsets_array[0]
    sr_corrected_audio = sr_original # Sample rate should be the same as original

    print(f"Cargando audio corregido desde: {corrected_audio_path}")
    # Load the corrected audio (stereo)
    y_corrected_stereo, _ = sf.read(corrected_audio_path, dtype='float32')
    # sf.read returns (samples, channels) for stereo, librosa usually (channels, samples). Transpose.
    y_corrected_stereo = y_corrected_stereo.T

    print(f"Visualizando {segment_duration:.2f} segundos del audio CORREGIDO en el ataque de nota: {first_onset_time:.2f} segundos")

    # Calculate the start and end sample indices for the segment
    start_sample = librosa.time_to_samples(first_onset_time, sr=sr_corrected_audio)
    end_sample = librosa.time_to_samples(first_onset_time + segment_duration, sr=sr_corrected_audio)

    # Ensure that the calculated end sample does not exceed the total length of y_corrected_stereo
    max_samples = y_corrected_stereo.shape[1]

    start_sample = min(max(0, start_sample), max_samples - 1)
    end_sample = min(max_samples, end_sample)

    # Adjust start_sample if end_sample becomes too close to max_samples
    if (end_sample - start_sample) < librosa.time_to_samples(segment_duration, sr=sr_corrected_audio):
        start_sample = max(0, end_sample - librosa.time_to_samples(segment_duration, sr=sr_corrected_audio))

    # Extract the stereo audio segment from the corrected audio
    y_segment_corrected_stereo = y_corrected_stereo[:, int(start_sample):int(end_sample)]

    # Create a time array for the x-axis for the segment
    time_vector = np.linspace(0, len(y_segment_corrected_stereo[0]) / sr_corrected_audio, num=len(y_segment_corrected_stereo[0]))

    # Generate the plot for both stereo channels using subplots
    fig, axes = plt.subplots(nrows=2, ncols=1, figsize=(14, 8), sharex=True)

    # Plot Left Channel
    axes[0].plot(time_vector, y_segment_corrected_stereo[0, :], color='blue')
    axes[0].set_title('Canal Izquierdo (Audio Corregido)')
    axes[0].set_ylabel('Amplitud')
    axes[0].grid(True)

    # Plot Right Channel
    axes[1].plot(time_vector, y_segment_corrected_stereo[1, :], color='red')
    axes[1].set_title('Canal Derecho (Audio Corregido)')
    axes[1].set_ylabel('Amplitud')
    axes[1].set_xlabel('Tiempo (s)') # Shared x-axis label
    axes[1].grid(True)

    plt.suptitle(f"Forma de Onda Estéreo Corregida ({segment_duration:.2f}s) desde el Primer Ataque de Nota ({first_onset_time:.2f}s)")
    plt.tight_layout(rect=[0, 0.03, 1, 0.95]) # Adjust layout to prevent suptitle overlap
    plt.show()

    print("✅ Visualización de la forma de onda estéreo del audio corregido completada.")
else:
    print("❌ ERROR: No se pudieron definir todas las variables necesarias para la visualización. Asegúrate de que los archivos de audio existan y los pasos previos se hayan ejecutado.")

"""Visualización de forma de onda"""

import matplotlib.pyplot as plt
import numpy as np
import librosa # Ensure librosa is imported for time_to_samples

# 1. Define the duration of the segment to visualize (in seconds)
segment_duration = 0.05 # Adjusted to 0.05 seconds as per subtask

# 2. Get the first onset time from the onsets_array
# Ensure onsets_array, y_original_stereo, and sr_original are available
if 'onsets_array' in globals() and len(globals()['onsets_array']) > 0 and \
   'y_original_stereo' in globals() and 'sr_original' in globals():

    first_onset_time = globals()['onsets_array'][0]
    sr_original_local = globals()['sr_original']
    y_original_stereo_local = globals()['y_original_stereo']

    print(f"Visualizando {segment_duration:.2f} segundos del ataque de nota en: {first_onset_time:.2f} segundos")

    # 3. Calculate the start and end sample indices for the segment
    start_sample = librosa.time_to_samples(first_onset_time, sr=sr_original_local)
    end_sample = librosa.time_to_samples(first_onset_time + segment_duration, sr=sr_original_local)

    # 4. Ensure that the calculated end sample does not exceed the total length of y_original_stereo
    max_samples = y_original_stereo_local.shape[1] # Total number of samples in the stereo audio

    start_sample = min(max(0, start_sample), max_samples - 1)
    end_sample = min(max_samples, end_sample)

    # Adjust start_sample if end_sample becomes too close to max_samples
    if (end_sample - start_sample) < librosa.time_to_samples(segment_duration, sr=sr_original_local):
        start_sample = max(0, end_sample - librosa.time_to_samples(segment_duration, sr=sr_original_local))

    # 5. Extract the stereo audio segment
    y_segment_stereo = y_original_stereo_local[:, int(start_sample):int(end_sample)]

    # 6. Create a time array for the x-axis for the segment
    time_vector = np.linspace(0, len(y_segment_stereo[0]) / sr_original_local, num=len(y_segment_stereo[0]))

    # 7. Generate the plot for both stereo channels using subplots
    fig, axes = plt.subplots(nrows=2, ncols=1, figsize=(14, 8), sharex=True)

    # Plot Left Channel
    axes[0].plot(time_vector, y_segment_stereo[0, :], color='blue')
    axes[0].set_title('Canal Izquierdo')
    axes[0].set_ylabel('Amplitud')
    axes[0].grid(True)

    # Plot Right Channel
    axes[1].plot(time_vector, y_segment_stereo[1, :], color='red')
    axes[1].set_title('Canal Derecho')
    axes[1].set_ylabel('Amplitud')
    axes[1].set_xlabel('Tiempo (s)') # Shared x-axis label
    axes[1].grid(True)

    plt.suptitle(f'Forma de Onda Estéreo ({segment_duration:.2f}s) desde el Primer Ataque de Nota ({first_onset_time:.2f}s)')
    plt.tight_layout(rect=[0, 0.03, 1, 0.95]) # Adjust layout to prevent suptitle overlap
    plt.show()

    print("✅ Visualización de la forma de onda estéreo completada.")
else:
    print("❌ ERROR: Variables necesarias (onsets_array, y_original_stereo, sr_original) no se encontraron o están vacías. Asegúrate de que las celdas de detección de onsets y carga de audio original se hayan ejecutado previamente.")

"""#### Sobre la detección de finales de nota (Offsets):

La detección de "offsets" (finales de nota) es generalmente más desafiante que la de "onsets". `librosa` no tiene una función directa y sencilla como `onset_detect` para los offsets.

Comúnmente, los offsets se pueden inferir de varias maneras:
1.  **Análisis de energía:** Buscando caídas significativas de energía después de un onset.
2.  **Segmentación:** Dividiendo el audio en segmentos donde cada segmento podría representar una nota, y luego los finales de esos segmentos serían los offsets.
3.  **Modelos más avanzados:** Usando técnicas de aprendizaje automático que han sido entrenadas para reconocer tanto el inicio como el final de los sonidos.

Si necesitas una detección precisa de offsets, se requeriría un procesamiento adicional que podría involucrar:
*   `librosa.effects.split()` para segmentar el audio basado en la energía.
*   Analizar el decaimiento de la energía o la envolvente de la señal después de cada onset.
"""

import librosa
import numpy as np

def detect_custom_offset(y_mono, sr, onset_sample, search_end_sample, threshold_ratio=0.05, min_frames_below_threshold=3):
    """
    Detecta el offset de una nota analizando su envolvente de energía (RMS).

    Args:
        y_mono (np.ndarray): El audio mono completo.
        sr (int): La tasa de muestreo del audio.
        onset_sample (int): El índice de muestra donde comienza la nota.
        search_end_sample (int): El índice de muestra hasta donde buscar el offset (ej. el siguiente onset o fin del audio).
        threshold_ratio (float): Proporción de la energía pico para establecer el umbral de offset.
        min_frames_below_threshold (int): Número mínimo de frames que la energía debe estar por debajo del umbral
                                          para considerar que el offset ha ocurrido.

    Returns:
        int: El índice de muestra estimado para el offset de la nota.
    """
    # Definir el segmento donde buscaremos el offset
    # Asegurarse de que el segmento de búsqueda no exceda los límites del audio
    search_segment_end = min(search_end_sample, len(y_mono))
    search_segment = y_mono[onset_sample:search_segment_end]

    if len(search_segment) == 0:
        return onset_sample # No hay audio en el segmento de búsqueda, el offset es el onset.

    # Parámetros para el cálculo de la energía RMS
    frame_length = 2048 # Tamaño de la ventana para FFT/análisis de energía
    hop_length = 512    # Paso para el cálculo de la energía

    # Si el segmento es demasiado corto para una trama, el offset es el final del segmento.
    if len(search_segment) < frame_length:
        return onset_sample + len(search_segment)

    # Calcular la energía RMS
    rms = librosa.feature.rms(y=search_segment, frame_length=frame_length, hop_length=hop_length)[0]

    if len(rms) == 0:
        return onset_sample # No se pudieron calcular frames RMS.

    # Encontrar la energía RMS pico en el segmento de búsqueda
    peak_rms = np.max(rms)
    if peak_rms == 0:
        return onset_sample + len(search_segment) # Evitar división por cero o umbral cero si el segmento es silencio

    # Calcular el umbral dinámico
    threshold = peak_rms * threshold_ratio

    # Buscar el primer frame donde la energía cae por debajo del umbral
    offset_frame = len(rms) - 1 # Por defecto, el offset es el final del segmento de búsqueda en frames
    found_sustained_drop = False

    for i in range(len(rms) - min_frames_below_threshold):
        if np.all(rms[i : i + min_frames_below_threshold] < threshold):
            offset_frame = i
            found_sustained_drop = True
            break

    # Si no se encuentra una caída sostenida, el offset puede ser el final del segmento
    # o un decaimiento muy gradual. En estos casos, usamos el final del segmento de búsqueda.
    if not found_sustained_drop:
        offset_frame = len(rms) - 1

    # Convertir el índice del frame de offset a un índice de muestra, relativo al inicio del search_segment
    offset_sample_in_search_segment = librosa.frames_to_samples(offset_frame, hop_length=hop_length)

    # Convertir a índice de muestra global en el audio original completo
    global_offset_sample = onset_sample + offset_sample_in_search_segment

    # Asegurarse de que el offset no exceda el límite del segmento de búsqueda
    global_offset_sample = min(global_offset_sample, search_end_sample)

    return int(global_offset_sample)

"""### Prueba de Detección de Onset y Offset de la Primera Nota

Esta sección cargará el archivo procesado, detectará el primer comienzo de nota (`onset`) y su final (`offset`), recortará esa porción de audio y la guardará como `Nota_C0_crop.wav`.
"""

import os
import librosa
import numpy as np
import soundfile as sf
import gc

# --- Configuración para la prueba ---
TEST_INPUT_FILE = "/content/drive/MyDrive/Processed_Audio_Colab/MVSep Piano UI/piano-model-mt-5-piano-mvsep.wav"
OUTPUT_CROP_NAME = "Nota_C0_crop.wav"

# Asegurarse de que CARPETA_SALIDA esté definida (del código principal)
# Si no lo estuviera, definir aquí:
CARPETA_SALIDA = "/content/drive/MyDrive/Processed_Audio_Colab/MVSep Piano UI/Separated_notes"
# Crear la carpeta de salida si no existe
os.makedirs(CARPETA_SALIDA, exist_ok=True)

if not os.path.exists(TEST_INPUT_FILE):
    print(f"❌ ERROR: El archivo de prueba no se encontró en {TEST_INPUT_FILE}. Asegúrate de que el procesamiento anterior se haya ejecutado correctamente.")
else:
    print(f"Cargando archivo para prueba de primera nota: {TEST_INPUT_FILE}")
    # Cargar como estéreo para mantener la información de ambos canales
    y_stereo, sr_test = librosa.load(TEST_INPUT_FILE, sr=None, mono=False)

    # Convertir a mono para la detección de onsets y offsets.
    y_test_mono = librosa.to_mono(y_stereo)

    print("1️⃣ Detectando onsets...")
    onsets_frames_test = librosa.onset.onset_detect(y=y_test_mono, sr=sr_test, units='frames', backtrack=True)
    onsets_times_test_raw = librosa.frames_to_time(onsets_frames_test, sr=sr_test)

    if len(onsets_times_test_raw) == 0:
        print("❌ No se detectaron onsets en el archivo de prueba. No se puede continuar.")
    else:
        first_onset_time = onsets_times_test_raw[0]

        # Asegurarse de que el sample index esté dentro de los límites del audio
        first_onset_sample = min(librosa.time_to_samples(first_onset_time, sr=sr_test), y_stereo.shape[1] - 1)
        print(f"   ✅ Primer onset detectado en: {first_onset_time:.2f} segundos")

        print("2️⃣ Intentando detectar el offset de la primera nota usando el método personalizado...")

        # Definir el final de la búsqueda para el offset (el siguiente onset o el final del audio)
        search_end_sample = y_test_mono.shape[0]
        if len(onsets_times_test_raw) > 1:
            next_onset_time = onsets_times_test_raw[1]
            search_end_sample = min(librosa.time_to_samples(next_onset_time, sr=sr_test), search_end_sample)

        # Usar la función personalizada para detectar el offset
        first_offset_sample = detect_custom_offset(y_test_mono, sr_test, first_onset_sample, search_end_sample, threshold_ratio=0.01, min_frames_below_threshold=5)

        if first_offset_sample == first_onset_sample:
            print("   ⚠️ No se pudo determinar un offset claro con la detección personalizada. Usando duración heurística de 2.0s.")
            first_offset_sample = first_onset_sample + int(2.0 * sr_test) # Duración fija de 2.0 segundos
            if first_offset_sample > y_stereo.shape[1]:
                first_offset_sample = y_stereo.shape[1]

        first_offset_time_raw = librosa.samples_to_time(first_offset_sample, sr=sr_test)

        print(f"   ✅ Offset de la primera nota estimado en: {first_offset_time_raw:.2f} segundos")

        print("3️⃣ Recortando y guardando la primera nota...")
        # Recortar el audio estéreo completo usando los índices de sample detectados
        cropped_note_stereo = y_stereo[:, int(first_onset_sample):int(librosa.time_to_samples(first_offset_time_raw, sr=sr_test))]

        output_path = os.path.join(CARPETA_SALIDA, OUTPUT_CROP_NAME)
        # sf.write espera (samples, channels) para estéreo, así que transponemos
        sf.write(output_path, cropped_note_stereo.T, sr_test)

        print(f"✅ ¡PRUEBA TERMINADA! Archivo '{OUTPUT_CROP_NAME}' guardado en: {output_path}")
        print(f"   La nota se extiende desde {first_onset_time:.2f}s hasta {first_offset_time_raw:.2f}s.")

        # Limpiar memoria
        del y_stereo, y_test_mono, cropped_note_stereo, onsets_times_test_raw, first_offset_time_raw
gc.collect()

from IPython.display import Audio
import os

# Ruta al archivo que quieres reproducir
audio_file_path = os.path.join(CARPETA_SALIDA, OUTPUT_CROP_NAME)

if os.path.exists(audio_file_path):
    print(f"Reproduciendo: {audio_file_path}")
    display(Audio(audio_file_path))
else:
    print(f"❌ ERROR: El archivo de audio no se encontró en {audio_file_path}. Asegúrate de que la prueba anterior se haya ejecutado correctamente.")

"""### Conteo y Gestión de Notas Procesadas

Esta sección analiza el array `all_notes_onsets_offsets_array` para contar el número total de notas detectadas y, si se desea, libera la memoria utilizada por este array.

## Actualizar Ruta de Audio Procesado
"""

import librosa
import numpy as np
import gc # Para liberar memoria
import os

# --- Nuevo: Ruta del archivo procesado para la segmentación (Corregida) ---
PROCESSED_FILE_FOR_SEGMENTATION = "/content/drive/MyDrive/Processed_Audio_Colab/MVSep Piano UI/piano-model-mt-5-piano-mvsep.wav"

# --- Comprobación de existencia del archivo procesado ---
if not os.path.exists(PROCESSED_FILE_FOR_SEGMENTATION):
    print(f"❌ ERROR: El archivo procesado no se encontró en {PROCESSED_FILE_FOR_SEGMENTATION}. Asegúrate de que el procesamiento anterior se haya ejecutado correctamente.")
    exit()
# --------------------------------------------------------------------------------------

print(f"Cargando archivo para detección de todas las notas desde: {PROCESSED_FILE_FOR_SEGMENTATION}")

# Cargar el audio. Para detección de onsets/offsets, librosa recomienda mono.
# Cargamos estéreo por si se necesita en el futuro, pero convertimos a mono para las detecciones.
y_all_stereo, sr_all = librosa.load(PROCESSED_FILE_FOR_SEGMENTATION, sr=None, mono=False)
y_all_mono = librosa.to_mono(y_all_stereo)

print("1️⃣ Detectando onsets para todas las notas...")
onsets_frames_all = librosa.onset.onset_detect(y=y_all_mono, sr=sr_all, units='frames')
onsets_times_all = librosa.frames_to_time(onsets_frames_all, sr=sr_all)

print(f"   Se detectaron {len(onsets_times_all)} onsets.")

print("2️⃣ Estimando offsets y recolectando pares (onset, offset) para todas las notas...")
notes_data = []

# Usamos librosa.effects.split en el audio mono para obtener segmentos de actividad.
# top_db ajustado a 50 para capturar decays más largos de piano.
segments = librosa.effects.split(y_all_mono, top_db=50)

for i, onset_time in enumerate(onsets_times_all):
    onset_sample = librosa.time_to_samples(onset_time, sr=sr_all)
    offset_sample = None

    # Buscar el segmento que contiene este onset
    for start_s, end_s in segments:
        if start_s <= onset_sample < end_s:
            offset_sample = end_s
            break

    # Fallback heurístico si no se encuentra un offset claro o si el onset está al final
    if offset_sample is None or offset_sample <= onset_sample:
        if i + 1 < len(onsets_times_all): # Si hay un siguiente onset, usarlo como límite
            next_onset_time = onsets_times_all[i+1]
            offset_sample = librosa.time_to_samples(next_onset_time, sr=sr_all)
        else: # Si es la última nota, usar una duración fija o el final del audio
            offset_sample = onset_sample + int(1.5 * sr_all) # Heurística de 1.5 segundos
            if offset_sample > y_all_mono.shape[0]:
                offset_sample = y_all_mono.shape[0]

    # Asegurarse de que el offset no exceda la longitud del audio
    offset_sample = min(offset_sample, y_all_mono.shape[0])

    offset_time = librosa.samples_to_time(offset_sample, sr=sr_all)
    notes_data.append((onset_time, offset_time))

# Convertir la lista de tuplas a un array de NumPy para fácil manipulación
all_notes_onsets_offsets_array = np.array(notes_data)

print(f"✅ Se han detectado y almacenado {len(all_notes_onsets_offsets_array)} pares (onset, offset).")
print("Primeros 10 onsets detectados (en segundos):")
print(all_notes_onsets_offsets_array[:10, 0]) # Mostrar solo la primera columna (onsets)

# Limpiar memoria de los audios cargados en esta celda (pero no el array all_notes_onsets_offsets_array)
del y_all_stereo, y_all_mono, onsets_frames_all, onsets_times_all, segments, notes_data
gc.collect()

import gc

# Asegurarse de que el array exista
if 'all_notes_onsets_offsets_array' in locals():
    cantidad_notas_procesadas = len(all_notes_onsets_offsets_array)
    print(f"✅ Cantidad de notas procesadas y almacenadas: {cantidad_notas_procesadas}")

    # Si deseas liberar el array de la memoria después de haberlo contabilizado y si no lo necesitas más:
    # Descomenta las siguientes líneas si estás seguro de que ya no necesitarás 'all_notes_onsets_offsets_array'
    # print("Liberando 'all_notes_onsets_offsets_array' de la memoria...")
    # del all_notes_onsets_offsets_array
    # gc.collect()
    # print("Array liberado (si se descomentaron las líneas).")
else:
    print("❌ El array 'all_notes_onsets_offsets_array' no se encontró. Asegúrate de que la celda de detección de notas se haya ejecutado previamente.")

"""### **Detección de Onsets y Offsets para Todas las Notas**

Esta sección cargará el archivo de audio principal (`ARCHIVO_INPUT`), detectará los comienzos (onsets) y estimará los finales (offsets) para cada nota, almacenando los pares de tiempo en un array.
"""

import librosa
import numpy as np
import gc # Para liberar memoria
import os
import shutil

# Asegurarse de que ARCHIVO_INPUT esté definido (tomado de la configuración anterior)
ARCHIVO_INPUT = "/content/drive/MyDrive/Processed_Audio_Colab/MVSep Piano UI/piano-model-mt-5-piano-mvsep.wav"

# --- Nuevo: Copiar archivo a un directorio local de Colab para evitar problemas con Drive ---
LOCAL_TEMP_AUDIO_PATH = "/content/temp_audio.wav"

print(f"Copiando el archivo desde Google Drive a {LOCAL_TEMP_AUDIO_PATH}...")
try:
    shutil.copy(ARCHIVO_INPUT, LOCAL_TEMP_AUDIO_PATH)
    print("Copia exitosa. Usando el archivo local para el procesamiento.")
except FileNotFoundError:
    print(f"❌ ERROR: El archivo de origen no se encontró en {ARCHIVO_INPUT}. Asegúrate de que exista en tu Drive.")
    exit()
except Exception as e:
    print(f"❌ Ocurrió un error al copiar el archivo: {e}")
    exit()
# --------------------------------------------------------------------------------------

print(f"Cargando archivo para detección de todas las notas desde: {LOCAL_TEMP_AUDIO_PATH}")

# Cargar el audio. Para detección de onsets/offsets, librosa recomienda mono.
# Cargamos estéreo por si se necesita en el futuro, pero convertimos a mono para las detecciones.
y_all_stereo, sr_all = librosa.load(LOCAL_TEMP_AUDIO_PATH, sr=None, mono=False)
y_all_mono = librosa.to_mono(y_all_stereo)

print("1️⃣ Detectando onsets para todas las notas...")
onsets_frames_all = librosa.onset.onset_detect(y=y_all_mono, sr=sr_all, units='frames', backtrack=True)
onsets_times_all_raw = librosa.frames_to_time(onsets_frames_all, sr=sr_all)

onsets_times_all = onsets_times_all_raw

print(f"   Se detectaron {len(onsets_times_all)} onsets.")

print("2️⃣ Estimando offsets y recolectando pares (onset, offset) para todas las notas usando el método personalizado...")
notes_data = []

for i, onset_time in enumerate(onsets_times_all):
    onset_sample = librosa.time_to_samples(onset_time, sr=sr_all)

    # Definir el final de la búsqueda para el offset (el siguiente onset o el final del audio)
    search_end_sample = y_all_mono.shape[0]
    if i + 1 < len(onsets_times_all):
        next_onset_time = onsets_times_all[i+1]
        search_end_sample = min(librosa.time_to_samples(next_onset_time, sr=sr_all), search_end_sample)

    # Usar la función personalizada para detectar el offset
    offset_sample = detect_custom_offset(y_all_mono, sr_all, onset_sample, search_end_sample, threshold_ratio=0.01, min_frames_below_threshold=5)

    # Fallback heurístico si no se encuentra un offset claro o si el offset es igual al onset
    if offset_sample == onset_sample:
        # Si es la última nota o la detección personalizada falla, usar una duración fija
        offset_sample = onset_sample + int(2.0 * sr_all) # Heurística de 2.0 segundos
        if offset_sample > y_all_mono.shape[0]:
            offset_sample = y_all_mono.shape[0]

    # Asegurarse de que el offset no exceda la longitud del audio
    offset_sample = min(offset_sample, y_all_mono.shape[0])

    offset_time_raw = librosa.samples_to_time(offset_sample, sr=sr_all)

    notes_data.append((onset_time, offset_time_raw))

# Convertir la lista de tuplas a un array de NumPy para fácil manipulación
all_notes_onsets_offsets_array = np.array(notes_data)

print(f"✅ Se han detectado y almacenado {len(all_notes_onsets_offsets_array)} pares (onset, offset).")
print("Primeros 10 onsets detectados (en segundos):")
print(all_notes_onsets_offsets_array[:10, 0]) # Mostrar solo la primera columna (onsets)

# Limpiar memoria de los audios cargados en esta celda (pero no el array all_notes_onsets_offsets_array)
del y_all_stereo, y_all_mono, onsets_frames_all, onsets_times_all_raw, notes_data, offset_time_raw
gc.collect()

"""###**Detección de Pitch y Nomenclatura de Notas**

Esta sección procesa cada nota detectada (definida por sus onsets y offsets) para determinar su pitch (frecuencia fundamental) y la convierte a un formato de nomenclatura musical (`octava-nota-intensidad`).
"""

import librosa
import numpy as np
import gc
import re # Para parsear la notación de nota y octava

# --- CONFIGURACIÓN DE INTENSIDAD ---
# Esta variable se usará para la etiqueta de intensidad. El usuario la modificará manualmente.
DEFAULT_INTENSITY_LABEL = "p" # Ejemplo: "p" para piano, "f" para forte, etc.

# Lista para almacenar la información de las notas detectadas (incluyendo repeticiones)
all_detected_note_labels = []

# Asegurarse de que PROCESSED_FILE_FOR_SEGMENTATION esté definido (redefinido para seguridad)
PROCESSED_FILE_FOR_SEGMENTATION = "/content/drive/MyDrive/Processed_Audio_Colab/MVSep Piano UI/piano-model-mt-5-piano-mvsep.wav"

# Asegurarse de que all_notes_onsets_offsets_array esté disponible
if 'all_notes_onsets_offsets_array' in locals() and len(all_notes_onsets_offsets_array) > 0:
    print(f"Iniciando detección de pitch para {len(all_notes_onsets_offsets_array)} segmentos de audio...")

    # Recargar el archivo de audio principal, ya que las variables de audio podrían haberse limpiado
    print(f"Cargando el archivo procesado para detección de pitch desde: {PROCESSED_FILE_FOR_SEGMENTATION}")
    y_all_stereo, sr_all = librosa.load(PROCESSED_FILE_FOR_SEGMENTATION, sr=None, mono=False)
    y_all_mono = librosa.to_mono(y_all_stereo)

    # Iterar sobre cada par (onset, offset) de nota detectado
    for i, (onset_time, offset_time) in enumerate(all_notes_onsets_offsets_array):
        # Convertir tiempos a muestras (samples)
        onset_sample = librosa.time_to_samples(onset_time, sr=sr_all)
        offset_sample = librosa.time_to_samples(offset_time, sr=sr_all)

        # Asegurarse de que los límites del segmento estén dentro de la longitud del audio
        onset_sample = max(0, onset_sample)
        offset_sample = min(len(y_all_mono), offset_sample)

        # Extraer el segmento de audio mono para la nota actual
        note_segment = y_all_mono[onset_sample:offset_sample]

        current_note_label = ""
        if len(note_segment) > 0:
            # Realizar detección de pitch usando librosa.pyin (más robusto que librosa.yin)
            f0, _, _ = librosa.pyin(
                y=note_segment,
                sr=sr_all,
                fmin=librosa.note_to_hz('A0'), # Límite inferior para piano
                fmax=librosa.note_to_hz('C8'), # Límite superior para piano
                frame_length=4096, # Aumentado para mejor detección de bajas frecuencias
                hop_length=1024     # Ajustado proporcionalmente
            )

            # Filtrar los pitches no detectados (NaN) y los valores cero
            f0_nonzero = f0[~np.isnan(f0) & (f0 > 0)]

            if len(f0_nonzero) > 0:
                # Tomar la mediana de las frecuencias fundamentales detectadas para robustez
                dominant_f0 = np.median(f0_nonzero)

                # Convertir frecuencia a notación de nota y octava (ej. 'C4', 'D#5')
                note_octave_str = librosa.hz_to_note(dominant_f0, cents=False)

                # Parsear 'C#4' en 'C#' (nota) y '4' (octava)
                # Actualizado para reconocer tanto '#' como '♯' (Unicode sharp)
                match = re.match(r"([A-G][b#♯]?)([0-9-]+)", note_octave_str)
                if match:
                    note = match.group(1)
                    octave = match.group(2)
                    # Nuevo formato: Nota-Octava-Intensidad
                    current_note_label = f"{note}-{octave}-{DEFAULT_INTENSITY_LABEL}"
                else:
                    current_note_label = f"PARSE_ERROR_{note_octave_str}-{DEFAULT_INTENSITY_LABEL}" # Fallback si hay error al parsear
            else:
                current_note_label = f"UNKNOWN_PITCH-{DEFAULT_INTENSITY_LABEL}" # Fallback si no se detecta pitch
        else:
            current_note_label = f"EMPTY_SEGMENT-{DEFAULT_INTENSITY_LABEL}" # Fallback para segmentos vacíos

        all_detected_note_labels.append(current_note_label)

    # Crear la lista final de notas únicas y ordenarlas
    all_notes_pitch_intensity_labels = sorted(list(set(all_detected_note_labels)))

    print(f"✅ Detección de pitch completada para {len(all_detected_note_labels)} segmentos detectados. Se encontraron {len(all_notes_pitch_intensity_labels)} notas únicas.")
    print("Primeros 10 elementos de la lista de notas *únicas* (formato Nota-Octava-Intensidad):")
    print(all_notes_pitch_intensity_labels[:10])

    # Limpiar memoria de los audios cargados en esta celda
    del y_all_stereo, y_all_mono
    gc.collect()

else:
    print("❌ El array 'all_notes_onsets_offsets_array' no se encontró o está vacío. Asegúrate de que la celda de detección de onsets/offsets se haya ejecutado previamente.")

"""### Identificación de Notas Reincidentes (Round Robins)"""

import collections
import numpy as np

# Asegurarse de que all_detected_note_labels esté disponible de la celda anterior
if 'all_detected_note_labels' in locals() and len(all_detected_note_labels) > 0:
    print("1️⃣ Contando la frecuencia de cada etiqueta de nota...")
    # Usar Counter para contar cuántas veces aparece cada etiqueta de nota
    note_counts = collections.Counter(all_detected_note_labels)

    # Crear el array round_robins con el formato solicitado
    round_robins = []
    for note_label, count in note_counts.items():
        round_robins.append(f"{note_label}-RR({count})")

    # Opcional: Ordenar alfabéticamente para una mejor visualización
    round_robins.sort()

    print(f"✅ Se han identificado {len(note_counts)} notas únicas y se han preparado para el array 'round_robins'.")
    print("Primeros 10 elementos del array 'round_robins':")
    print(round_robins[:10])

    # Mostrar el total de elementos en round_robins
    print(f"\nTotal de elementos en round_robins: {len(round_robins)}")

else:
    print("❌ La lista 'all_detected_note_labels' no se encontró o está vacía. Asegúrate de que la celda de 'Detección de Pitch y Nomenclatura de Notas' se haya ejecutado previamente.")

"""## **Configurar y Crear Carpeta de Salida de notas**

### Subtask:
Definir la ruta de la carpeta de salida en Google Drive. La carpeta se llamará 'PIANO' (derivado de la intensidad 'p') y estará ubicada en /content/drive/MyDrive/Processed_Audio_Colab. Se asegurará de que esta carpeta exista.

"""

import os

# Ruta base donde se procesarán los audios
BASE_OUTPUT_FOLDER_DRIVE = "/content/drive/MyDrive/Processed_Audio_Colab"

# Nombre de la carpeta de salida específica para las notas de piano
NOTE_INTENSITY_FOLDER_NAME = "PIANO"

# Ruta completa de la carpeta de salida para las notas
CARPETA_SALIDA_NOTAS = os.path.join(BASE_OUTPUT_FOLDER_DRIVE, NOTE_INTENSITY_FOLDER_NAME)

# Crear la carpeta de salida si no existe
os.makedirs(CARPETA_SALIDA_NOTAS, exist_ok=True)

print(f"✅ Carpeta de salida para notas creada/verificada en: {CARPETA_SALIDA_NOTAS}")

import os
import librosa
import numpy as np
import soundfile as sf
import gc
import re # Needed for parsing note names from labels

# --- Nueva: Ruta del archivo procesado para la segmentación (Corregida) ---
PROCESSED_FILE_FOR_SEGMENTATION = "/content/drive/MyDrive/Processed_Audio_Colab/MVSep Piano UI/piano-model-mt-5-piano-mvsep.wav"

# Asegurarse de que las variables necesarias estén disponibles
# CARPETA_SALIDA_NOTAS (definida en el paso anterior)
# all_notes_onsets_offsets_array (definido en 'Detección de Onsets y Offsets para Todas las Notas')
# all_detected_note_labels (definido en 'Detección de Pitch y Nomenclatura de Notas')
# all_notes_pitch_intensity_labels (definido en 'Detección de Pitch y Nomenclatura de Notas', contiene UNIQUE notes)

if not all(v in globals() for v in ['CARPETA_SALIDA_NOTAS', 'all_notes_onsets_offsets_array', 'all_detected_note_labels', 'all_notes_pitch_intensity_labels']):
    print("❌ ERROR: Una o más variables esenciales no se encontraron. Asegúrate de que los pasos anteriores se hayan ejecutado correctamente.")
else:
    print(f"Cargando el audio original para el recorte de notas desde: {PROCESSED_FILE_FOR_SEGMENTATION}")
    try:
        # Reload the full stereo audio
        y_full_audio, sr_full_audio = librosa.load(PROCESSED_FILE_FOR_SEGMENTATION, sr=None, mono=False)
        print(f"Audio cargado con éxito. Sample rate: {sr_full_audio} Hz")
    except Exception as e:
        print(f"❌ ERROR al cargar el audio original: {e}")
        exit()

    # Dictionary to count repetitions for simplified filenames to avoid collisions
    filename_collision_counter = {}
    processed_files_count = 0
    errors_count = 0

    print(f"Iniciando el procesamiento de {len(all_notes_pitch_intensity_labels)} notas *únicas*...")

    # Iterate over each UNIQUE note label (e.g., 'C#-4-p')
    for i, unique_note_label in enumerate(all_notes_pitch_intensity_labels):
        try:
            # Find the FIRST occurrence of this unique_note_label in the full list of detected labels
            # This gives us the index to retrieve its onset/offset times
            # Use a list comprehension to find all indices where the unique_note_label appears
            matching_indices = [idx for idx, label in enumerate(all_detected_note_labels) if label == unique_note_label]

            if not matching_indices:
                print(f"⚠️ Advertencia: La etiqueta de nota única '{unique_note_label}' no se encontró en all_detected_note_labels. Saltando.")
                errors_count += 1
                continue

            # Use the first occurrence to get the onset/offset time for the segment
            first_occurrence_index = matching_indices[0]
            onset_time, offset_time = all_notes_onsets_offsets_array[first_occurrence_index]

            # Convert times to samples
            onset_sample = librosa.time_to_samples(onset_time, sr=sr_full_audio)
            offset_sample = librosa.time_to_samples(offset_time, sr=sr_full_audio)

            # Ensure limits are within full audio length
            onset_sample = max(0, onset_sample)
            offset_sample = min(y_full_audio.shape[1], offset_sample)

            # Extract the stereo audio segment for the current note
            cropped_note_audio = y_full_audio[:, onset_sample:offset_sample]

            # --- Filename Generation Logic (simplified and collision-aware) ---
            # Example unique_note_label: 'C#-4-p'
            match = re.match(r"([A-G][b#♯]?)(-?[0-9]+)-(.*)", unique_note_label)
            if match:
                original_note_name_part = match.group(1) # e.g., 'C', 'C#', 'Db'
                octave_part = match.group(2)            # e.g., '4' or '-1'

                intensity_part = match.group(3)         # e.g., 'p'

                # NEW: Strip leading hyphens from octave_part for filename
                octave_part_cleaned = octave_part.lstrip('-')

                # Determine if the note is altered
                is_altered = '#' in original_note_name_part or 'b' in original_note_name_part or '♯' in original_note_name_part
                altered_suffix = '_A' if is_altered else ''

                # Get the natural note equivalent for the filename (strip all accidentals)
                natural_note_for_filename = original_note_name_part.replace('#', '').replace('♯', '').replace('b', '')

                # Construct the base filename segment
                base_filename_segment = f"{natural_note_for_filename}_{octave_part_cleaned}_{intensity_part}"

                # Combine with altered suffix
                full_base_filename = f"{base_filename_segment}{altered_suffix}"

                # Handle collisions: increment counter for this full base filename
                # The counter should reflect the total number of times this specific note label appears in `all_detected_note_labels`
                # We need to consider all occurrences, not just the first one.
                # However, the previous logic was for *unique* filenames based on the unique_note_label.
                # If the goal is to save only one file per unique_note_label, the original counter logic was fine.
                # If the goal is to save ALL occurrences of notes, then `all_notes_pitch_intensity_labels` should not be iterated.
                # Assuming the previous goal of saving unique note *types*, the `filename_collision_counter` logic for *these* unique names is retained.

                # To handle "Round Robins" for file naming correctly if multiple physical files are desired for the same 'C-4-p' label.
                # Currently, `filename_collision_counter` implicitly creates `C_4_p.wav`, `C_4_p_2.wav`, etc. based on parsing the first occurrence.
                # For this task, we are processing `all_notes_pitch_intensity_labels` which contains UNIQUE labels.
                # So, each `unique_note_label` should correspond to a single output file with its derived name.
                # The collision counter should be based on the number of actual unique note labels.

                # The previous agent's implementation of filename_collision_counter was implicitly handling cases where
                # different `unique_note_label`s might resolve to the same `full_base_filename` (e.g., C# and Db might both become C_A).
                # To be explicit about "unique note files", we should assign each unique_note_label a filename.
                # Let's simplify this: the filename should directly reflect the `unique_note_label` and not use a separate collision counter
                # if we are truly iterating over unique labels.

                # Simplified filename for unique labels
                output_filename = f"{natural_note_for_filename}_{octave_part_cleaned}_{intensity_part}{altered_suffix}.wav"
            else:
                # Fallback for unexpected unique_note_label format
                output_filename = f"UNPARSED_NOTE_{i}.wav"
                print(f"   ⚠️ Advertencia: No se pudo parsear la etiqueta de nota única '{unique_note_label}'. Usando nombre de archivo fallback.")
            # --- End Filename Generation Logic ---

            output_path = os.path.join(CARPETA_SALIDA_NOTAS, output_filename)

            # Save the WAV file
            sf.write(output_path, cropped_note_audio.T, sr_full_audio)
            processed_files_count += 1

            if (processed_files_count % 10 == 0) or (processed_files_count == len(all_notes_pitch_intensity_labels)):
                print(f"   ✅ Procesado y guardado {processed_files_count} / {len(all_notes_pitch_intensity_labels)} notas únicas. Última: {output_filename}")

        except Exception as e:
            errors_count += 1
            print(f"❌ ERROR al procesar la nota única {i+1} ({unique_note_label}): {e}")

    print("\n--- RESUMEN DEL PROCESAMIENTO DE NOTAS ÚNICAS ---")
    print(f"Total de notas únicas procesadas y guardadas: {processed_files_count}")
    print(f"Notas con errores (no guardadas): {errors_count}")
    print(f"Archivos de notas guardados en: {CARPETA_SALIDA_NOTAS}")

    # Clean up memory
    del y_full_audio, cropped_note_audio
    gc.collect()

import librosa
import numpy as np
import gc # Para liberar memoria
import os

# --- Nuevo: Ruta del archivo procesado para la segmentación (Corregida) ---
PROCESSED_FILE_FOR_SEGMENTATION = "/content/drive/MyDrive/Processed_Audio_Colab/MVSep Piano UI/piano-model-mt-5-piano-mvsep.wav"

# --- Comprobación de existencia del archivo procesado ---
if not os.path.exists(PROCESSED_FILE_FOR_SEGMENTATION):
    print(f"❌ ERROR: El archivo procesado no se encontró en {PROCESSED_FILE_FOR_SEGMENTATION}. Asegúrate de que el procesamiento anterior se haya ejecutado correctamente.")
    exit()
# --------------------------------------------------------------------------------------

print(f"Cargando archivo para detección de todas las notas desde: {PROCESSED_FILE_FOR_SEGMENTATION}")

# Cargar el audio. Para detección de onsets/offsets, librosa recomienda mono.
# Cargamos estéreo por si se necesita en el futuro, pero convertimos a mono para las detecciones.
y_all_stereo, sr_all = librosa.load(PROCESSED_FILE_FOR_SEGMENTATION, sr=None, mono=False)
y_all_mono = librosa.to_mono(y_all_stereo)

print("1️⃣ Detectando onsets para todas las notas...")
onsets_frames_all = librosa.onset.onset_detect(y=y_all_mono, sr=sr_all, units='frames')
onsets_times_all = librosa.frames_to_time(onsets_frames_all, sr=sr_all)

print(f"   Se detectaron {len(onsets_times_all)} onsets.")

print("2️⃣ Estimando offsets y recolectando pares (onset, offset) para todas las notas...")
notes_data = []

# Usamos librosa.effects.split en el audio mono para obtener segmentos de actividad.
# top_db ajustado a 50 para capturar decays más largos de piano.
segments = librosa.effects.split(y_all_mono, top_db=50)

for i, onset_time in enumerate(onsets_times_all):
    onset_sample = librosa.time_to_samples(onset_time, sr=sr_all)
    offset_sample = None

    # Buscar el segmento que contiene este onset
    for start_s, end_s in segments:
        if start_s <= onset_sample < end_s:
            offset_sample = end_s
            break

    # Fallback heurístico si no se encuentra un offset claro o si el onset está al final
    if offset_sample is None or offset_sample <= onset_sample:
        if i + 1 < len(onsets_times_all): # Si hay un siguiente onset, usarlo como límite
            next_onset_time = onsets_times_all[i+1]
            offset_sample = librosa.time_to_samples(next_onset_time, sr=sr_all)
        else: # Si es la última nota, usar una duración fija o el final del audio
            offset_sample = onset_sample + int(1.5 * sr_all) # Heurística de 1.5 segundos
            if offset_sample > y_all_mono.shape[0]:
                offset_sample = y_all_mono.shape[0]

    # Asegurarse de que el offset no exceda la longitud del audio
    offset_sample = min(offset_sample, y_all_mono.shape[0])

    offset_time = librosa.samples_to_time(offset_sample, sr=sr_all)
    notes_data.append((onset_time, offset_time))

# Convertir la lista de tuplas a un array de NumPy para fácil manipulación
all_notes_onsets_offsets_array = np.array(notes_data)

print(f"✅ Se han detectado y almacenado {len(all_notes_onsets_offsets_array)} pares (onset, offset).")
print("Primeros 10 onsets detectados (en segundos):")
print(all_notes_onsets_offsets_array[:10, 0]) # Mostrar solo la primera columna (onsets)

# Limpiar memoria de los audios cargados en esta celda (pero no el array all_notes_onsets_offsets_array)
del y_all_stereo, y_all_mono, onsets_frames_all, onsets_times_all, segments, notes_data
gc.collect()

# @title Actualizar Ruta de Audio Procesado y Corregir Nombres de Archivo (Celda 7d64a5ed)
# Modificando cell_id: 7d64a5ed

import os
import librosa
import numpy as np
import soundfile as sf
import gc
import re # Needed for parsing note names from labels

# --- Nueva: Ruta del archivo procesado para la segmentación (Corregida) ---
PROCESSED_FILE_FOR_SEGMENTATION = "/content/drive/MyDrive/Processed_Audio_Colab/MVSep Piano UI/piano-model-mt-5-piano-mvsep.wav"

# Asegurarse de que las variables necesarias estén disponibles
# CARPETA_SALIDA_NOTAS (definida en el paso anterior)
# all_notes_onsets_offsets_array (definido en 'Detección de Onsets y Offsets para Todas las Notas')
# all_detected_note_labels (definido en 'Detección de Pitch y Nomenclatura de Notas')
# all_notes_pitch_intensity_labels (definido en 'Detección de Pitch y Nomenclatura de Notas', contiene UNIQUE notes)

if not all(v in globals() for v in ['CARPETA_SALIDA_NOTAS', 'all_notes_onsets_offsets_array', 'all_detected_note_labels', 'all_notes_pitch_intensity_labels']):
    print("❌ ERROR: Una o más variables esenciales no se encontraron. Asegúrate de que los pasos anteriores se hayan ejecutado correctamente.")
else:
    print(f"Cargando el audio original para el recorte de notas desde: {PROCESSED_FILE_FOR_SEGMENTATION}")
    try:
        # Reload the full stereo audio
        y_full_audio, sr_full_audio = librosa.load(PROCESSED_FILE_FOR_SEGMENTATION, sr=None, mono=False)
        print(f"Audio cargado con éxito. Sample rate: {sr_full_audio} Hz")
    except Exception as e:
        print(f"❌ ERROR al cargar el audio original: {e}")
        exit()

    # Dictionary to count repetitions for simplified filenames to avoid collisions
    filename_collision_counter = {}
    processed_files_count = 0
    errors_count = 0

    print(f"Iniciando el procesamiento de {len(all_notes_pitch_intensity_labels)} notas *únicas*...")

    # Iterate over each UNIQUE note label (e.g., 'C#-4-p')
    for i, unique_note_label in enumerate(all_notes_pitch_intensity_labels):
        try:
            # Find the FIRST occurrence of this unique_note_label in the full list of detected labels
            # This gives us the index to retrieve its onset/offset times
            # Use a list comprehension to find all indices where the unique_note_label appears
            matching_indices = [idx for idx, label in enumerate(all_detected_note_labels) if label == unique_note_label]

            if not matching_indices:
                print(f"⚠️ Advertencia: La etiqueta de nota única '{unique_note_label}' no se encontró en all_detected_note_labels. Saltando.")
                errors_count += 1
                continue

            # Use the first occurrence to get the onset/offset time for the segment
            first_occurrence_index = matching_indices[0]
            onset_time, offset_time = all_notes_onsets_offsets_array[first_occurrence_index]

            # Convert times to samples
            onset_sample = librosa.time_to_samples(onset_time, sr=sr_full_audio)
            offset_sample = librosa.time_to_samples(offset_time, sr=sr_full_audio)

            # Ensure limits are within full audio length
            onset_sample = max(0, onset_sample)
            offset_sample = min(y_full_audio.shape[1], offset_sample)

            # Extract the stereo audio segment for the current note
            cropped_note_audio = y_full_audio[:, onset_sample:offset_sample]

            # --- Filename Generation Logic (simplified and collision-aware) ---
            # Example unique_note_label: 'C#-4-p'
            match = re.match(r"([A-G][b#♯]?)(-?[0-9]+)-(.*)", unique_note_label)
            if match:
                original_note_name_part = match.group(1) # e.g., 'C', 'C#', 'Db'
                octave_part = match.group(2)            # e.g., '4' or '-1'
                intensity_part = match.group(3)         # e.g., 'p'

                # NEW: Strip leading hyphens from octave_part for filename
                octave_part_cleaned = octave_part.lstrip('-')

                # Determine if the note is altered
                is_altered = '#' in original_note_name_part or 'b' in original_note_name_part or '♯' in original_note_name_part
                altered_suffix = '_A' if is_altered else ''

                # Get the natural note equivalent for the filename (strip all accidentals)
                natural_note_for_filename = original_note_name_part.replace('#', '').replace('♯', '').replace('b', '')

                # Construct the base filename segment
                base_filename_segment = f"{natural_note_for_filename}_{octave_part_cleaned}_{intensity_part}"

                # Combine with altered suffix
                full_base_filename = f"{base_filename_segment}{altered_suffix}"

                # Handle collisions: increment counter for this full base filename
                # The counter should reflect the total number of times this specific note label appears in `all_detected_note_labels`
                # We need to consider all occurrences, not just the first one.
                # However, the previous logic was for *unique* filenames based on the unique_note_label.
                # If the goal is to save only one file per unique_note_label, the original counter logic was fine.
                # If the goal is to save ALL occurrences of notes, then `all_notes_pitch_intensity_labels` should not be iterated.
                # Assuming the previous goal of saving unique note *types*, the `filename_collision_counter` logic for *these* unique names is retained.

                # To handle "Round Robins" for file naming correctly if multiple physical files are desired for the same 'C-4-p' label.
                # Currently, `filename_collision_counter` implicitly creates `C_4_p.wav`, `C_4_p_2.wav`, etc. based on parsing the first occurrence.
                # For this task, we are processing `all_notes_pitch_intensity_labels` which contains UNIQUE labels.
                # So, each `unique_note_label` should correspond to a single output file with its derived name.
                # The collision counter should be based on the number of actual unique note labels.

                # The previous agent's implementation of filename_collision_counter was implicitly handling cases where
                # different `unique_note_label`s might resolve to the same `full_base_filename` (e.g., C# and Db might both become C_A).
                # To be explicit about "unique note files", we should assign each unique_note_label a filename.
                # Let's simplify this: the filename should directly reflect the `unique_note_label` and not use a separate collision counter
                # if we are truly iterating over unique labels.

                # Simplified filename for unique labels
                output_filename = f"{natural_note_for_filename}_{octave_part_cleaned}_{intensity_part}{altered_suffix}.wav"
            else:
                # Fallback for unexpected unique_note_label format
                output_filename = f"UNPARSED_NOTE_{i}.wav"
                print(f"   ⚠️ Advertencia: No se pudo parsear la etiqueta de nota única '{unique_note_label}'. Usando nombre de archivo fallback.")
            # --- End Filename Generation Logic ---

            output_path = os.path.join(CARPETA_SALIDA_NOTAS, output_filename)

            # Save the WAV file
            sf.write(output_path, cropped_note_audio.T, sr_full_audio)
            processed_files_count += 1

            if (processed_files_count % 10 == 0) or (processed_files_count == len(all_notes_pitch_intensity_labels)):
                print(f"   ✅ Procesado y guardado {processed_files_count} / {len(all_notes_pitch_intensity_labels)} notas únicas. Última: {output_filename}")

        except Exception as e:
            errors_count += 1
            print(f"❌ ERROR al procesar la nota única {i+1} ({unique_note_label}): {e}")

    print("\n--- RESUMEN DEL PROCESAMIENTO DE NOTAS ÚNICAS ---")
    print(f"Total de notas únicas procesadas y guardadas: {processed_files_count}")
    print(f"Notas con errores (no guardadas): {errors_count}")
    print(f"Archivos de notas guardados en: {CARPETA_SALIDA_NOTAS}")

    # Clean up memory
    del y_full_audio, cropped_note_audio
    gc.collect()